# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - node/install-packages:
          pkg-manager: yarn
          app-dir: "backend"
      - run:
          command: yarn run build-gatsby
          name: Build app
      - run: sudo yarn global add serverless@3.22.0
      - run: # print the name of the branch we're on
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      # deploy to AWS
      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              cd backend && yarn run deploy --stage prod 
            else
              cd backend && yarn run deploy --stage $(echo $CIRCLE_SHA1 | cut -c -7)
            fi
