# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - node/install-packages:
          pkg-manager: npm
          app-dir: "~/backend"
      - run:
          command: npm run build
          name: Build app
      - run: sudo npm install serverless -g
      # deploy to AWS
      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              cd backend && npm run deploy -- --stage prod 
            else
              cd backend && npm run deploy -- --stage $(echo $CIRCLE_SHA1 | cut -c -7)
            fi
